// Turns one room asset into paste-ready code. Pure on purpose so it runs in
// the browser (Copy code) and under `node --test`.

const ASPECT = /^(\d+):(\d+)$/;

function words(label) {
  return String(label || "motion").match(/[A-Za-z0-9]+/g) || ["motion"];
}

export function componentName(label) {
  const name = words(label).map((word) => word[0].toUpperCase() + word.slice(1).toLowerCase()).join("");
  return /^[A-Za-z]/.test(name) ? name : `Motion${name}`;
}

export function elementName(label) {
  return `skeleton-motion-${words(label).join("-").toLowerCase()}`;
}

function ratioOf(variant) {
  const match = String(variant.format || "").match(ASPECT);
  return match ? Number(match[1]) / Number(match[2]) : variant.width / variant.height;
}

/**
 * Pairs light/dark files per frame shape, primary (first listed) shape first.
 * @param variants room variants: { file, format, theme, width, height }
 */
export function groupVariants(variants) {
  const shapes = new Map();
  for (const variant of variants) {
    const key = variant.format || `${variant.width}x${variant.height}`;
    const shape = shapes.get(key) || { aspect: key, ratio: Number(ratioOf(variant).toFixed(4)) };
    shape[variant.theme === "dark" ? "dark" : "light"] = variant.file;
    shapes.set(key, shape);
  }
  return [...shapes.values()].filter((shape) => shape.light || shape.dark);
}

// The exported SVGs render through <img> data URIs: each instance stays
// isolated (no clashing ids or styles) and nothing is injected as HTML.
// Inside an HTML <script>, "</" must not appear or the string could end the element.
function literal(value, inHtml) {
  const json = JSON.stringify(value);
  return inHtml ? json.replace(/<\//g, "<\\/") : json;
}

function variantsLiteral(shapes, svgByFile, indent, inHtml = false) {
  const pad = " ".repeat(indent);
  return shapes.map((shape) => {
    const light = svgByFile[shape.light || shape.dark];
    const dark = svgByFile[shape.dark || shape.light];
    return `${pad}{\n${pad}  aspect: ${JSON.stringify(shape.aspect)},\n${pad}  ratio: ${shape.ratio},\n${pad}  light: ${literal(light, inHtml)},\n${pad}  dark: ${literal(dark, inHtml)},\n${pad}},`;
  }).join("\n");
}

function header(label, shapes) {
  return `${label}, generated by Skeleton Motion. Shapes: ${shapes.map((shape) => shape.aspect).join(", ")}.`;
}

/**
 * @param svgByFile SVG markup keyed by variant file name.
 * @returns React component source (JSX, no dependencies beyond React).
 */
export function reactCode({ label, alt, shapes, svgByFile }) {
  const name = componentName(label);
  // "use client" lets Next.js App Router pages import it; other setups ignore it.
  return `"use client";

// ${header(label, shapes)}
// Shows the shape closest to its box (or the one in \`aspect\`) and follows
// the system color scheme unless \`theme\` is "light" or "dark". Visitors
// who prefer reduced motion see the opening frame, still.
import { useEffect, useMemo, useRef, useState } from "react";

const VARIANTS = [
${variantsLiteral(shapes, svgByFile, 2)}
];

const toSrc = (svg) => \`data:image/svg+xml;charset=utf-8,\${encodeURIComponent(svg)}\`;
// Without its animate elements the SVG shows its opening frame.
const still = (svg) => svg.replace(/<animate(?:Transform|Motion)?\\b[^>]*\\/>/g, "");

const closest = (ratio) =>
  VARIANTS.reduce((best, item) => (Math.abs(Math.log(item.ratio / ratio)) < Math.abs(Math.log(best.ratio / ratio)) ? item : best));

function useMedia(query) {
  const [matches, setMatches] = useState(false);
  useEffect(() => {
    const media = window.matchMedia(query);
    const update = () => setMatches(media.matches);
    update();
    media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, [query]);
  return matches;
}

function usePrefersDark(theme) {
  const [dark, setDark] = useState(theme === "dark");
  useEffect(() => {
    if (theme !== "auto") {
      setDark(theme === "dark");
      return undefined;
    }
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const update = () => setDark(media.matches);
    update();
    media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, [theme]);
  return dark;
}

export default function ${name}({ aspect = "auto", theme = "auto", alt = ${JSON.stringify(alt)}, className, style }) {
  const box = useRef(null);
  const [measured, setMeasured] = useState(null);
  const dark = usePrefersDark(theme);
  const calm = useMedia("(prefers-reduced-motion: reduce)");

  useEffect(() => {
    if (aspect !== "auto" || !box.current) return undefined;
    const observer = new ResizeObserver(([entry]) => {
      const { width, height } = entry.contentRect;
      if (width > 0 && height > 0) setMeasured(width / height);
    });
    observer.observe(box.current);
    return () => observer.disconnect();
  }, [aspect]);

  const variant = VARIANTS.find((item) => item.aspect === aspect) || (measured ? closest(measured) : VARIANTS[0]);
  const src = useMemo(() => {
    const svg = dark ? variant.dark : variant.light;
    return toSrc(calm ? still(svg) : svg);
  }, [variant, dark, calm]);

  // Full width by default; aspect-ratio then sets the height only when none is
  // given, so a box with its own height keeps it and gets the closest shape.
  return (
    <div ref={box} className={className} style={{ width: "100%", aspectRatio: variant.ratio, ...style }}>
      <img src={src} alt={alt} style={{ display: "block", width: "100%", height: "100%", objectFit: "contain" }} />
    </div>
  );
}
`;
}

/**
 * @returns HTML snippet: one custom element plus its module script, no build step.
 */
export function htmlCode({ label, alt, shapes, svgByFile }) {
  const tag = elementName(label);
  const className = `${componentName(label)}Element`;
  return `<!-- ${header(label, shapes)}
     Attributes: aspect="auto|${shapes.map((shape) => shape.aspect).join("|")}", theme="auto|light|dark". -->
<${tag} theme="auto" style="display: block; width: 100%"></${tag}>

<script type="module">
  const VARIANTS = [
${variantsLiteral(shapes, svgByFile, 4, true)}
  ];

  const toSrc = (svg) => \`data:image/svg+xml;charset=utf-8,\${encodeURIComponent(svg)}\`;
  // Without its animate elements the SVG shows its opening frame.
  const still = (svg) => svg.replace(/<animate(?:Transform|Motion)?\\b[^>]*\\/>/g, "");
  const closest = (ratio) =>
    VARIANTS.reduce((best, item) => (Math.abs(Math.log(item.ratio / ratio)) < Math.abs(Math.log(best.ratio / ratio)) ? item : best));

  class ${className} extends HTMLElement {
    static observedAttributes = ["aspect", "theme"];

    connectedCallback() {
      // Custom elements are inline by default, and inline boxes ignore
      // aspect-ratio; full width keeps a given height from widening the box.
      this.style.display ||= "block";
      this.style.width ||= "100%";
      this.img ||= Object.assign(document.createElement("img"), { alt: ${JSON.stringify(alt)} });
      Object.assign(this.img.style, { display: "block", width: "100%", height: "100%", objectFit: "contain" });
      this.append(this.img);
      this.media = window.matchMedia("(prefers-color-scheme: dark)");
      this.calm = window.matchMedia("(prefers-reduced-motion: reduce)");
      this.onScheme = () => this.render();
      this.media.addEventListener("change", this.onScheme);
      this.calm.addEventListener("change", this.onScheme);
      this.observer = new ResizeObserver(([entry]) => {
        const { width, height } = entry.contentRect;
        if (width > 0 && height > 0) this.measured = width / height;
        this.render();
      });
      this.observer.observe(this);
      this.render();
    }

    disconnectedCallback() {
      this.observer?.disconnect();
      this.media?.removeEventListener("change", this.onScheme);
      this.calm?.removeEventListener("change", this.onScheme);
    }

    attributeChangedCallback() {
      if (this.img) this.render();
    }

    render() {
      const aspect = this.getAttribute("aspect") || "auto";
      const theme = this.getAttribute("theme") || "auto";
      const variant = VARIANTS.find((item) => item.aspect === aspect) || (this.measured ? closest(this.measured) : VARIANTS[0]);
      const dark = theme === "dark" || (theme === "auto" && this.media.matches);
      this.style.aspectRatio = String(variant.ratio);
      const svg = dark ? variant.dark : variant.light;
      const src = toSrc(this.calm.matches ? still(svg) : svg);
      if (this.img.src !== src) this.img.src = src;
    }
  }

  if (!customElements.get(${JSON.stringify(tag)})) customElements.define(${JSON.stringify(tag)}, ${className});
</script>
`;
}
