#!/usr/bin/env node
// Builds src/library/icons.js, the engine's icon vocabulary, from an
// unpacked lucide-static package (ISC). Only the curated names below ship:
// each is a name the story model may choose, so the list stays short.
//
//   npm pack lucide-static && tar -xzf lucide-static-*.tgz -C /tmp/lucide
//   node scripts/build-icons.mjs /tmp/lucide/package

import fs from "node:fs/promises";
import path from "node:path";

// Icons a product story reaches for, grouped by what they show.
const CURATED = [
  // reactions and saving
  "heart", "star", "bookmark", "thumbs-up", "bell", "flag", "pin", "smile", "trophy",
  // media
  "music", "play", "pause", "mic", "headphones", "volume-2", "audio-lines", "video", "image", "camera",
  // files and sharing
  "file", "file-text", "folder", "upload", "download", "cloud", "link", "share-2", "send", "copy", "printer",
  // messaging
  "mail", "message-circle", "phone",
  // time and place
  "calendar", "clock", "map-pin", "navigation", "car", "plane", "truck", "globe", "house",
  // commerce
  "shopping-cart", "shopping-bag", "credit-card", "wallet", "tag", "gift", "receipt", "ticket", "package",
  // people and access
  "user", "users", "user-plus", "lock", "shield-check", "key",
  // tools and data
  "search", "funnel", "settings", "sliders-horizontal", "chart-column", "trending-up", "zap", "sparkles", "bot",
  "code", "terminal", "git-branch", "git-pull-request", "database", "server", "layout-grid", "list", "rocket", "eye",
  "sun", "moon", "wifi", "battery-full",
  // edits
  "check", "x", "plus", "trash-2", "pencil", "refresh-cw",
];

// Closed outlines that read as "on" when filled. The first shape is the
// outline; any later shapes are details drawn over the fill.
const FILLABLE = new Set(["heart", "star", "bookmark", "thumbs-up", "bell", "flag", "map-pin", "message-circle", "tag", "shield-check", "ticket"]);

const SHAPE = /<(path|circle|rect|line|polyline|polygon|ellipse)\s([^>]*?)\/>/g;
const ATTRIBUTE = /([a-z-]+)="([^"]*)"/g;

function shapes(svg) {
  return [...svg.matchAll(SHAPE)].map(([, tag, attributes]) => [tag, Object.fromEntries([...attributes.matchAll(ATTRIBUTE)].map(([, name, value]) => [name, value]))]);
}

const [source] = process.argv.slice(2);
if (!source) {
  console.error("usage: build-icons.mjs <unpacked lucide-static package dir>");
  process.exit(1);
}
const { version } = JSON.parse(await fs.readFile(path.join(source, "package.json"), "utf8"));
const license = (await fs.readFile(path.join(source, "LICENSE"), "utf8")).split("\n---")[0].trim();
const tags = JSON.parse(await fs.readFile(path.join(source, "tags.json"), "utf8"));

const icons = {};
for (const name of CURATED) {
  const svg = await fs.readFile(path.join(source, "icons", `${name}.svg`), "utf8");
  icons[name] = { fill: FILLABLE.has(name), nodes: shapes(svg), tags: (tags[name] || []).slice(0, 8) };
}

const out = `// Generated by scripts/build-icons.mjs from lucide-static ${version}. Do not edit.
// 24x24 stroke icons, drawn by src/library/draw-icon.js.
//
${license.split("\n").map((line) => `// ${line}`.trimEnd()).join("\n")}

export const ICONS = Object.freeze(${JSON.stringify(icons, null, 1).replace(/\n\s*/g, " ")});

export const ICON_NAMES = Object.freeze(Object.keys(ICONS));
`;
await fs.mkdir(new URL("../src/library/", import.meta.url), { recursive: true });
await fs.writeFile(new URL("../src/library/icons.js", import.meta.url), out);
console.log(`${CURATED.length} icons from lucide-static ${version}`);
